language: node_js

node_js:
  - stable

script: make lint test

addons:
  code_climate:
    repo_token: 69b8b7d4f7a9955ff0aef90ba49a1f0016f68e5f6f1ad764c98a5f6cbb7bc975s

after_success:
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
  - istanbul cover node_modules/jest/bin/jest.js -- --coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
